@startuml
title OrderTaker: Food Ordering API - Entity Relationship Diagram
skinparam linetype ortho
hide circle

entity "Users" as user {
    * **userId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * username : VARCHAR(45)
    * email : VARCHAR(254)
    * passwordHash : VARCHAR(60)
    * role : VARCHAR(20)
    * createdAt : DATETIME
}

entity "Customers" as customer {
    * **customerId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * customerName: VARCHAR(45)
    * address1 : VARCHAR(100)
    * address2 : VARCHAR(100)
    * userId : BIGINT(20) <<FK, Users>>
    * isActive : BOOLEAN
}

entity "Restaurants" as resto {
    * **restaurantId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * restaurantName : VARCHAR(45)
    * address1 : VARCHAR(100)
    * address2 : VARCHAR(100)
    * ownerId : BIGINT(20) <<FK, Users>>
    * isActive : BOOLEAN
}

entity "MenuItems" as menu {
    * **menuItemId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * restaurantId : BIGINT(20) << FK, Restaurants>>
    * name : VARCHAR(45)
    * description : VARCHAR(254)
    * price : DECIMAL(15,2)
    * isAvailable : BOOLEAN
}

entity "Orders" as order {
    * **orderId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * customerId : BIGINT(20) <<FK, Customers>>
    * restaurantId : BIGINT(20) <<FK, Restaurants>>
    * status : VARCHAR(20)
    * totalAmount : DECIMAL(15,2)
    * createdAt : DATETIME
}

entity "OrderItems" as item {
    * **orderItemId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * orderId : BIGINT(20) <<FK, Orders>>
    * menuItemId : BIGINT(20) <<FK, MenuItems>>
    * quantity : INT(3)
    * priceAtOrderTime : DECIMAL(15,2)
}

entity "Carts" as cart {
    * **orderId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * customerId : BIGINT(20) <<FK, Customers>>
    * restaurantId : BIGINT(20) <<FK, Restaurants>>
    * status : VARCHAR(20)
    * totalAmount : DECIMAL(15,2)
    * createdAt : DATETIME
}

entity "CartItems" as cartitem {
    * **cartItemId** : BIGINT(20) <<PK, AUTO_INCREMENT>>
    --
    * cartId : BIGINT(20) <<FK, Orders>>
    * menuItemId : BIGINT(20) <<FK, MenuItems>>
    * quantity : INT(3)
    * priceAtOrderTime : DECIMAL(15,2)
}

user ||--o|resto
user ||--o| customer
resto ||--o{ menu
customer ||--o{ order
resto ||--o{ order
order ||--{ item
menu ||--o{ item
customer ||--o| cart
resto ||--o{ cart
cart ||--o{ cartitem
menu ||--o{ cartitem

@enduml